#!/bin/sh

wget -o /tmp/pkgs.tar.gz https://github.com/fly/burrepo/archive/master.tar.gz
cd /tmp/
tar -xf /tmp/pkgs.tar.gz
cp /tmp/burrepo-master/pkgs/*.pkg.tar.xz /srv/burrepo/
/usr/bin/repo-add /srv/burrepo/burrepo.db.tar.gz /srv/burrepo/*.pkg.tar.xz
echo "done adding packages."
